"use client";
import { FormEvent, useState } from "react";
import Image from "next/image";
import { ArrowRight, Check, Heart, MessageCircle, ShieldCheck, Sparkles, Stethoscope, CalendarDays, MapPin, Camera } from "lucide-react";

const services = [
  { icon: Sparkles, title: "Estética do sorriso", text: "Planejamento individual para um sorriso natural, equilibrado e compatível com você." },
  { icon: ShieldCheck, title: "Prevenção e cuidado", text: "Acompanhamento atento para preservar sua saúde bucal em todas as fases da vida." },
  { icon: Stethoscope, title: "Avaliação completa", text: "Uma consulta cuidadosa para entender suas necessidades e indicar o melhor caminho." },
];

export default function Home() {
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  async function submitContact(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("loading"); const form = event.currentTarget;
    try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); if (!response.ok) throw new Error(); setStatus("success"); form.reset(); }
    catch { setStatus("error"); }
  }
  return <main>
    <header className="nav-wrap"><a className="brand" href="#inicio" aria-label="Início"><span className="brand-mark">AC</span><span><strong>Dra. Ana Carolina</strong><small>Cirurgiã-Dentista</small></span></a><nav aria-label="Navegação principal"><a href="#sobre">Sobre</a><a href="#cuidados">Cuidados</a><a href="#contato">Contato</a></nav><a className="nav-cta" href="#contato">Agendar avaliação</a></header>
    <section className="hero" id="inicio"><Image className="hero-image" src="/images/ana-hero.jpg" alt="Consultório odontológico moderno" fill priority sizes="100vw"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow"><span/> Odontologia com cuidado e propósito</p><h1>Seu sorriso merece um olhar <em>atento a cada detalhe.</em></h1><p className="hero-copy">Atendimento acolhedor, planejamento individual e cuidado profissional para você se sentir seguro em cada etapa.</p><div className="hero-actions"><a className="button primary" href="#contato">Agendar minha avaliação <ArrowRight size={18}/></a><a className="button ghost" href="#sobre">Conheça o atendimento</a></div><div className="trust-line"><span><Check size={16}/> Atendimento individualizado</span><span><Check size={16}/> Ambiente acolhedor</span></div></div></section>
    <section className="intro section" id="sobre"><div className="section-label">01 — A profissional</div><div className="intro-copy"><p className="kicker">Cuidado que começa pela escuta</p><h2>Mais tranquilidade para cuidar da sua saúde bucal.</h2></div><div className="intro-detail"><p>Sou Ana Carolina, cirurgiã-dentista. Acredito em uma odontologia próxima, clara e responsável — da primeira conversa ao acompanhamento de cada resultado.</p><p>Aqui, cada paciente é recebido com tempo, atenção e um plano de cuidado construído para suas necessidades.</p><div className="signature">Ana Carolina <span>Cirurgiã-Dentista</span></div></div></section>
    <section className="care-section" id="cuidados"><div className="section care-heading"><div><p className="kicker light">Cuidado em cada fase</p><h2>Uma experiência pensada para você.</h2></div><p>Informação clara, escuta e acompanhamento para decisões mais seguras sobre o seu sorriso.</p></div><div className="section service-grid">{services.map(({icon: Icon,title,text},index)=><article className="service-card" key={title}><span className="service-number">0{index+1}</span><Icon size={28}/><h3>{title}</h3><p>{text}</p><a href="#contato">Quero saber mais <ArrowRight size={16}/></a></article>)}</div></section>
    <section className="journey section"><div><p className="kicker">Simples e acolhedor</p><h2>Como funciona o primeiro atendimento?</h2></div><div className="steps"><div><span>1</span><h3>Conte o que você precisa</h3><p>Preencha o formulário com seus dados e o motivo do contato.</p></div><div><span>2</span><h3>Escolha o melhor horário</h3><p>Nossa equipe retorna para combinar a disponibilidade.</p></div><div><span>3</span><h3>Faça sua avaliação</h3><p>Converse com a doutora e receba uma orientação individual.</p></div></div></section>
    <section className="contact" id="contato"><div className="contact-inner section"><div className="contact-copy"><p className="kicker light">Comece por uma conversa</p><h2>Pronto para cuidar do seu sorriso?</h2><p>Envie seus dados e entraremos em contato para organizar sua avaliação.</p><div className="contact-notes"><span><MessageCircle size={20}/> Retorno pelo WhatsApp</span><span><CalendarDays size={20}/> Horário combinado com você</span><span><Heart size={20}/> Atendimento humanizado</span></div></div><form onSubmit={submitContact} className="contact-form"><label>Seu nome<input name="name" required minLength={2} placeholder="Como podemos chamar você?"/></label><label>WhatsApp<input name="phone" required minLength={8} placeholder="(00) 00000-0000" inputMode="tel"/></label><label>Como podemos ajudar?<select name="interest" required defaultValue=""><option value="" disabled>Selecione uma opção</option><option>Avaliação odontológica</option><option>Estética do sorriso</option><option>Prevenção e acompanhamento</option><option>Outro assunto</option></select></label><label>Mensagem (opcional)<textarea name="message" rows={3} placeholder="Conte um pouco sobre o que você procura"/></label><label className="consent"><input type="checkbox" name="consent" required/> Autorizo o contato sobre este atendimento.</label><button className="button form-button" disabled={status==="loading"}>{status==="loading"?"Enviando...":"Solicitar contato"}<ArrowRight size={18}/></button><p className={`form-status ${status}`} aria-live="polite">{status==="success"?"Recebemos seus dados. Em breve entraremos em contato.":status==="error"?"Não foi possível enviar agora. Tente novamente em instantes.":"Seus dados serão usados apenas para responder ao seu contato."}</p></form></div></section>
    <footer className="footer section"><div className="brand"><span className="brand-mark dark">AC</span><span><strong>Dra. Ana Carolina</strong><small>Cirurgiã-Dentista</small></span></div><div className="footer-info"><span><MapPin size={17}/> Local de atendimento a confirmar</span><span><Camera size={17}/> Instagram a confirmar</span></div><p>© 2026 Ana Carolina. Conteúdo demonstrativo sujeito à validação profissional.</p></footer>
  </main>;
}
